name: Auto release
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Initialization environment
        run: |
          # sudo curl -L -o /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg http://download.proxmox.com/debian/proxmox-release-bullseye.gpg
          # sudo chmod +r /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
          # sudo chmod a+w /etc/apt/sources.list
          # sudo echo "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription" >>/etc/apt/sources.list

          sudo apt-get update
          sudo apt-get install devscripts debhelper equivs git dwarves
          sudo apt-get autoremove --purge
          sudo apt-get clean

      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive
            path: pve-edge-kernel

      - name: Build
        run: |
          cd pve-edge-kernel
          debian/rules debian/control
          sudo mk-build-deps -i
          debuild --jobs=auto -b -uc -us

      - name: Upload artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          path: "*.deb"

      - name: Release
        run: |
          cd pve-edge-kernel
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="ci-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="Auto-Release $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create $(for a in ../*.deb; do echo -a $a; done) -t "$GITHUB_SHA" "$tag" -m "$message"
        env:
          GITHUB_TOKEN: ${{ github.token }}
